name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set executable permissions for scripts
        run: |
          git update-index --chmod=+x bin/brakeman
          git update-index --chmod=+x bin/importmap
          git update-index --chmod=+x bin/rubocop
          git update-index --chmod=+x bin/rails
          git update-index --chmod=+x bin/rake
          git update-index --chmod=+x bin/setup

      - name: Run setup script
        run: |
              chmod=+x bin/setup
              bin/setup

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bundle exec bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set executable permissions for scripts
        run: |
          git update-index --chmod=+x bin/importmap
          git update-index --chmod=+x bin/rails

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bundle exec bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec bin/rubocop

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ci_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set executable permissions for bin/rails
        run: git update-index --chmod=+x bin/rails

      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec bin/rails db:setup

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec bin/rails test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
