name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: Set executable permissions for scripts
        run: |
          chmod +x bin/brakeman
          chmod +x bin/importmap
          chmod +x bin/rubocop
          chmod +x bin/rails
          chmod +x bin/rake
          chmod +x bin/setup

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bundle exec bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set executable permissions for scripts
        run: |
          chmod +x bin/importmap
          chmod +x bin/rails

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bundle exec bin/importmap audit

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      


  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set executable permissions for bin/rails
        run: chmod +x bin/rails

      - name: Set up the database
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create
          bin/rails db:migrate

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

